import { useMemo } from 'react';

/**
 * PSO Dashboard Component
 * 
 * Main dashboard showing the matplotlib real-time visualization generated from the backend.
 * Matches the layout and style of the Osdag desktop version as requested.
 */
function PSODashboard({ data, onClose, optimizationDone }) {
  // Extract data from the props
  const { plotImage, globalBest, current_iter } = data || {};

  return (
    <div className="flex flex-col h-[600px] bg-white rounded-lg overflow-hidden border border-gray-200 shadow-xl">
      {/* Header Info Bar */}
      <div className="bg-[#6B7D20] px-4 py-2 flex items-center gap-6 border-b-2 border-[#556619]">
        <div className="text-white font-bold text-sm tracking-wide">
          ITERATION: {current_iter !== undefined ? current_iter + 1 : 0}
        </div>
        
        {globalBest && (
          <>
            <div className="text-[#FFD700] font-bold text-sm tracking-wide">
              BEST: {globalBest.weight_kg?.toFixed(0) || '---'} kg
            </div>
            <div className="text-white/80 text-xs font-medium">
              PARTICLE: {(globalBest.particle !== undefined ? globalBest.particle + 1 : '---')} @ Iter {(globalBest.iter !== undefined ? globalBest.iter + 1 : '---')}
            </div>
          </>
        )}
      </div>

      {/* Main Content Area */}
      <div className="flex-1 relative bg-white overflow-hidden flex items-center justify-center p-2">
        {!plotImage ? (
          <div className="flex flex-col items-center justify-center gap-4 text-gray-400">
            <div className="w-12 h-12 border-4 border-gray-200 border-t-[#6B7D20] rounded-full animate-spin" />
            <div className="text-lg font-medium animate-pulse">Initializing Matplotlib Visualization...</div>
            <div className="flex flex-col items-center gap-1 text-[10px] uppercase font-bold tracking-widest opacity-60">
                <span>Data Status:</span>
                <div className="flex gap-3">
                   <span className={plotImage ? "text-green-500" : "text-red-400"}>Plot: {plotImage ? "OK" : "MISSING"}</span>
                   <span className={globalBest ? "text-green-500" : "text-red-400"}>Best: {globalBest ? "OK" : "MISSING"}</span>
                   <span className={data.currentSwarm?.length > 0 ? "text-green-500" : "text-red-400"}>Swarm: {data.currentSwarm?.length > 0 ? "OK" : "MISSING"}</span>
                </div>
            </div>
            <p className="text-sm text-gray-400">Waiting for first iteration to be generated by backend</p>
          </div>
        ) : (
          <div className="w-full h-full flex items-center justify-center">
            <img 
              src={`data:image/png;base64,${plotImage}`} 
              alt="PSO Real-time Visualization" 
              className="max-w-full max-h-full object-contain shadow-sm border border-gray-100"
              style={{ minHeight: '400px' }}
            />
          </div>
        )}
      </div>

      {/* Footer Status Bar */}
      <div className="bg-white px-4 py-1.5 border-t border-gray-100 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className={`w-2 h-2 rounded-full ${optimizationDone ? 'bg-green-500' : 'bg-blue-500 animate-pulse'}`} />
          <span className="text-[10px] text-gray-500 font-medium">
            {optimizationDone ? 'Optimization Complete' : 'Optimizing Plate Girder... (Real-time Matplotlib Stream)'}
          </span>
        </div>
        
        <div className="flex items-center gap-4 text-[9px] font-bold text-gray-600 uppercase tracking-tighter">
           <span className="text-[#FFD700]">★</span> Best  
           <span className="text-[#6B8E23] px-1">◯</span> Feasible  
           <span className="text-[#F87171] px-1">◯</span> Infeasible
        </div>

        {optimizationDone && (
          <button 
            onClick={() => {
              const link = document.createElement('a');
              link.href = `data:image/png;base64,${plotImage}`;
              link.download = `pso_optimization_result.png`;
              link.click();
            }}
            className="text-[10px] bg-gray-50 hover:bg-gray-100 border border-gray-200 px-2 py-0.5 rounded transition-colors flex items-center gap-1 text-gray-700"
          >
            💾 Save Plot
          </button>
        )}
      </div>
    </div>
  );
}

export default PSODashboard;
